coverage:
  status:
    patch: no
    changes: no
    project:
      default: false
      tconnectsync:
        paths:
        - "tconnectsync/"
        target: '60%'
        threshold: '5%'
      tests:
        paths:
        - "tests/"
        target: '95%'
        threshold: '5%'